import { useEffect, useState } from 'react';
import { ChevronRight, Eye, Database, Cpu, FileText } from 'lucide-react';
import { supabase } from '../lib/supabase';

interface Props {
  snapshotId: string;
  onContinue: () => void;
}

export default function AITransparencyPage({ snapshotId, onContinue }: Props) {
  const [inputData, setInputData] = useState<any>(null);
  const [analysisLogic, setAnalysisLogic] = useState<string>('');
  const [outputData, setOutputData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadTransparencyData();
  }, [snapshotId]);

  const loadTransparencyData = async () => {
    try {
      const { data } = await supabase
        .from('macro_snapshots')
        .select('analysis_input_data, analysis_logic, analysis_output_data')
        .eq('id', snapshotId)
        .single();

      if (data) {
        setInputData(data.analysis_input_data);
        setAnalysisLogic(data.analysis_logic || 'No analysis logic recorded');
        setOutputData(data.analysis_output_data);
      }
    } catch (error) {
      console.error('Error loading transparency data:', error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 flex items-center justify-center">
        <div className="text-slate-600">Loading transparency data...</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 py-8 px-4">
      <div className="max-w-7xl mx-auto">
        <div className="mb-8">
          <div className="flex items-center gap-3 mb-3">
            <Eye className="w-8 h-8 text-blue-600" />
            <h1 className="text-3xl font-bold text-slate-900">AI Analysis Transparency</h1>
          </div>
          <p className="text-slate-600">Complete visibility into the data, logic, and output used to generate recommendations</p>
        </div>

        <div className="space-y-6">
          <div className="bg-white rounded-xl shadow-md overflow-hidden">
            <div className="bg-blue-600 px-6 py-4 flex items-center gap-3">
              <Database className="w-6 h-6 text-white" />
              <h2 className="text-xl font-bold text-white">Input Data: Macro Analysis Snapshot</h2>
            </div>
            <div className="p-6">
              <p className="text-sm text-slate-600 mb-4">
                This is all the data collected from your questionnaire responses and AI analysis that was used as input for generating recommendations.
              </p>
              <div className="bg-slate-50 rounded-lg p-4 border border-slate-200">
                <pre className="text-xs text-slate-800 overflow-x-auto whitespace-pre-wrap font-mono">
                  {inputData ? JSON.stringify(inputData, null, 2) : 'No input data available'}
                </pre>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-md overflow-hidden">
            <div className="bg-green-600 px-6 py-4 flex items-center gap-3">
              <Cpu className="w-6 h-6 text-white" />
              <h2 className="text-xl font-bold text-white">Analysis Logic: How Recommendations Are Generated</h2>
            </div>
            <div className="p-6">
              <p className="text-sm text-slate-600 mb-4">
                This describes the rules and logic used to analyze the input data and generate investment recommendations.
              </p>
              <div className="bg-slate-50 rounded-lg p-4 border border-slate-200">
                <div className="prose prose-sm max-w-none text-slate-800">
                  <pre className="text-sm whitespace-pre-wrap font-sans leading-relaxed">
                    {analysisLogic}
                  </pre>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-md overflow-hidden">
            <div className="bg-purple-600 px-6 py-4 flex items-center gap-3">
              <FileText className="w-6 h-6 text-white" />
              <h2 className="text-xl font-bold text-white">Output: Generated Recommendations</h2>
            </div>
            <div className="p-6">
              <p className="text-sm text-slate-600 mb-4">
                These are the final investment recommendations generated by analyzing the input data with the logic described above.
              </p>
              <div className="bg-slate-50 rounded-lg p-4 border border-slate-200">
                <pre className="text-xs text-slate-800 overflow-x-auto whitespace-pre-wrap font-mono">
                  {outputData ? JSON.stringify(outputData, null, 2) : 'No output data available'}
                </pre>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-8 bg-white rounded-xl shadow-md p-6">
          <button
            onClick={onContinue}
            className="w-full px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center gap-2 font-semibold"
          >
            Continue to Asset Data
            <ChevronRight className="w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
}
